"""Added leaderboard representation

Revision ID: 0dec3654dcf7
Revises: ef326e466ed9
Create Date: 2021-09-30 23:41:19.348718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dec3654dcf7'
down_revision = 'ef326e466ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leaderboard_speed', table_name='leaderboard')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_leaderboard_speed', 'leaderboard', ['speed'], unique=False)
    # ### end Alembic commands ###
