"""Changed leaderboard

Revision ID: 21cbd647e066
Revises: 35487950b065
Create Date: 2021-10-01 09:04:22.468267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21cbd647e066'
down_revision = '35487950b065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leaderboard_username', table_name='leaderboard')
    op.drop_column('leaderboard', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaderboard', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_leaderboard_username', 'leaderboard', ['username'], unique=False)
    # ### end Alembic commands ###
